language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
dist: bionic
sudo: true
# install dev dependencies
before_install:
  - pip install pytest-cov
  - pip install codecov
# install dependencies
install:
  - python setup.py install
# run tests
script:
  - pytest --cov=./
# upload coverage reports
after_success:
  - codecov
